title: Myself
author: Arslan Ali
email: melvi.gis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 this is to tell about myself. who am I, and what do I do. 
# social links
github_username:  Melvi05
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
